# Generated by Django 5.2.14 on 2026-06-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('stock_name', models.CharField(blank=True, max_length=160)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('watch', 'Watch'), ('active', 'Active'), ('closed', 'Closed')], default='watch', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('stock_name', models.CharField(blank=True, max_length=160)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('check_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.CharField(blank=True, max_length=160)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(default='unknown', max_length=16)),
                ('device_label', models.CharField(default='Unknown device', max_length=48)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_stocks_created_ea9610_idx'), models.Index(fields=['symbol', 'created_at'], name='core_stocks_symbol_124aad_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_stocks_ip_addr_67db0c_idx')],
            },
        ),
    ]
