# Generated by Django 5.2.14 on 2026-05-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('stock_name', models.CharField(blank=True, max_length=160)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('watch', 'Watch'), ('active', 'Active'), ('closed', 'Closed')], default='watch', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
