# Generated by Django 5.2.14 on 2026-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.CharField(blank=True, max_length=160)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(default='unknown', max_length=16)),
                ('device_label', models.CharField(default='Unknown device', max_length=48)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='market_stoc_created_cd4db4_idx'), models.Index(fields=['symbol', 'created_at'], name='market_stoc_symbol_807536_idx'), models.Index(fields=['ip_address', 'created_at'], name='market_stoc_ip_addr_51dafe_idx')],
            },
        ),
    ]
